#############################################################################
# Makefile for building: QGroundControl
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  G:\qgroundcontrol-Stable_V3.0\qgroundcontrol.pro
# Template: app
# Command: F:\Qt\Qt5.5.1\5.5\msvc2013\bin\qmake.exe -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=declarative_debug" "CONFIG+=qml_debug" -o Makefile G:\qgroundcontrol-Stable_V3.0\qgroundcontrol.pro
#############################################################################

MAKEFILE      = Makefile

first: debug
install: debug-install
uninstall: debug-uninstall
QMAKE         = F:\Qt\Qt5.5.1\5.5\msvc2013\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		debug \
		release


debug: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: G:\qgroundcontrol-Stable_V3.0\qgroundcontrol.pro F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\win32-msvc2013\qmake.conf F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\spec_pre.prf \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\common\msvc-desktop.conf \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\qconfig.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dcollision.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dcollision_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dcore.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dcore_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dinput.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dinput_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dlogic.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dlogic_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dquick.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dquick_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dquickrenderer.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dquickrenderer_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3drenderer.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3drenderer_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_axbase.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_axbase_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_axcontainer.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_axcontainer_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_axserver.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_axserver_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_bluetooth.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_bluetooth_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_bootstrap_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_clucene_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_concurrent.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_concurrent_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_core.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_core_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_dbus.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_dbus_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_declarative.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_declarative_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_designer.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_designer_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_designercomponents_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_enginio.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_enginio_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_gui.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_gui_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_help.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_help_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_location.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_location_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_multimedia.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_multimedia_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_multimediawidgets.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_network.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_network_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_nfc.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_nfc_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_opengl.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_opengl_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_openglextensions.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_openglextensions_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_platformsupport_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_positioning.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_positioning_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_printsupport.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_printsupport_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_qml.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_qml_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_qmltest.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_qmltest_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_quick.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_quick_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_quickparticles_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_quickwidgets.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_script.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_script_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_scripttools.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_scripttools_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_sensors.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_sensors_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_serialport.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_serialport_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_sql.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_sql_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_svg.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_svg_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_testlib.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_testlib_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_uiplugin.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_uitools.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_uitools_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webchannel.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webchannel_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webengine.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webengine_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webenginecore.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webenginecore_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webenginewidgets.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webenginewidgets_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webkit.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webkit_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webkitwidgets.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webkitwidgets_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_websockets.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_websockets_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webview_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_widgets.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_widgets_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_winextras.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_winextras_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_xml.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_xml_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_xmlpatterns.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\qt_functions.prf \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\qt_config.prf \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\win32\qt_config.prf \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\win32-msvc2013\qmake.conf \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\spec_post.prf \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\exclusive_builds.prf \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\default_pre.prf \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\win32\default_pre.prf \
		G:\qgroundcontrol-Stable_V3.0\QGCCommon.pri \
		G:\qgroundcontrol-Stable_V3.0\libs\qextserialport\src\qextserialport.pri \
		G:\qgroundcontrol-Stable_V3.0\src\QtLocationPlugin\QGCLocationPlugin.pri \
		G:\qgroundcontrol-Stable_V3.0\libs\qwt.pri \
		G:\qgroundcontrol-Stable_V3.0\QGCExternalLibs.pri \
		G:\qgroundcontrol-Stable_V3.0\src\VideoStreaming\VideoStreaming.pri \
		G:\qgroundcontrol-Stable_V3.0\QGCSetup.pri \
		G:\qgroundcontrol-Stable_V3.0\QGCInstaller.pri \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\resolve_config.prf \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\exclusive_builds_post.prf \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\default_post.prf \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\win32\console.prf \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\c++11.prf \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\qt.prf \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\resources.prf \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\moc.prf \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\testlib_defines.prf \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\win32\opengl.prf \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\uic.prf \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\qml_debug.prf \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\declarative_debug.prf \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\win32\rtti.prf \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\precompile_header.prf \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\warn_on.prf \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\testcase_targets.prf \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\exceptions.prf \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\yacc.prf \
		F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\lex.prf \
		G:\qgroundcontrol-Stable_V3.0\qgroundcontrol.pro \
		F:/Qt/Qt5.5.1/5.5/msvc2013/lib/Qt5Location.prl \
		F:/Qt/Qt5.5.1/5.5/msvc2013/lib/Qt5QuickWidgets.prl \
		F:/Qt/Qt5.5.1/5.5/msvc2013/lib/Qt5Quick.prl \
		F:/Qt/Qt5.5.1/5.5/msvc2013/lib/Qt5OpenGL.prl \
		F:/Qt/Qt5.5.1/5.5/msvc2013/lib/Qt5Svg.prl \
		F:/Qt/Qt5.5.1/5.5/msvc2013/lib/Qt5PrintSupport.prl \
		F:/Qt/Qt5.5.1/5.5/msvc2013/lib/Qt5Widgets.prl \
		F:/Qt/Qt5.5.1/5.5/msvc2013/lib/Qt5Gui.prl \
		F:/Qt/Qt5.5.1/5.5/msvc2013/lib/Qt5Concurrent.prl \
		F:/Qt/Qt5.5.1/5.5/msvc2013/lib/Qt5Positioning.prl \
		F:/Qt/Qt5.5.1/5.5/msvc2013/lib/Qt5Qml.prl \
		F:/Qt/Qt5.5.1/5.5/msvc2013/lib/Qt5Network.prl \
		F:/Qt/Qt5.5.1/5.5/msvc2013/lib/Qt5Sql.prl \
		F:/Qt/Qt5.5.1/5.5/msvc2013/lib/Qt5Xml.prl \
		F:/Qt/Qt5.5.1/5.5/msvc2013/lib/Qt5SerialPort.prl \
		F:/Qt/Qt5.5.1/5.5/msvc2013/lib/Qt5Test.prl \
		F:/Qt/Qt5.5.1/5.5/msvc2013/lib/Qt5Core.prl
	$(QMAKE) -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=declarative_debug" "CONFIG+=qml_debug" -o Makefile G:\qgroundcontrol-Stable_V3.0\qgroundcontrol.pro
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\spec_pre.prf:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\common\msvc-desktop.conf:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\qconfig.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dcollision.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dcollision_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dcore.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dcore_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dinput.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dinput_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dlogic.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dlogic_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dquick.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dquick_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dquickrenderer.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dquickrenderer_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3drenderer.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3drenderer_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_axbase.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_axbase_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_axcontainer.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_axcontainer_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_axserver.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_axserver_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_bluetooth.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_bluetooth_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_bootstrap_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_clucene_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_concurrent.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_concurrent_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_core.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_core_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_dbus.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_dbus_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_declarative.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_declarative_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_designer.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_designer_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_designercomponents_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_enginio.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_enginio_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_gui.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_gui_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_help.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_help_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_location.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_location_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_multimedia.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_multimedia_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_multimediawidgets.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_network.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_network_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_nfc.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_nfc_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_opengl.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_opengl_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_openglextensions.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_openglextensions_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_platformsupport_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_positioning.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_positioning_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_printsupport.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_printsupport_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_qml.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_qml_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_qmldevtools_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_qmltest.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_qmltest_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_quick.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_quick_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_quickparticles_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_quickwidgets.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_quickwidgets_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_script.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_script_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_scripttools.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_scripttools_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_sensors.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_sensors_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_serialport.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_serialport_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_sql.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_sql_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_svg.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_svg_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_testlib.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_testlib_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_uiplugin.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_uitools.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_uitools_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webchannel.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webchannel_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webengine.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webengine_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webenginecore.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webenginecore_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webenginewidgets.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webenginewidgets_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webkit.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webkit_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webkitwidgets.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webkitwidgets_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_websockets.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_websockets_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webview_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_widgets.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_widgets_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_winextras.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_winextras_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_xml.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_xml_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_xmlpatterns.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\qt_functions.prf:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\qt_config.prf:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\win32\qt_config.prf:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\win32-msvc2013\qmake.conf:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\spec_post.prf:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\exclusive_builds.prf:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\default_pre.prf:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\win32\default_pre.prf:
G:\qgroundcontrol-Stable_V3.0\QGCCommon.pri:
G:\qgroundcontrol-Stable_V3.0\libs\qextserialport\src\qextserialport.pri:
G:\qgroundcontrol-Stable_V3.0\src\QtLocationPlugin\QGCLocationPlugin.pri:
G:\qgroundcontrol-Stable_V3.0\libs\qwt.pri:
G:\qgroundcontrol-Stable_V3.0\QGCExternalLibs.pri:
G:\qgroundcontrol-Stable_V3.0\src\VideoStreaming\VideoStreaming.pri:
G:\qgroundcontrol-Stable_V3.0\QGCSetup.pri:
G:\qgroundcontrol-Stable_V3.0\QGCInstaller.pri:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\resolve_config.prf:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\exclusive_builds_post.prf:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\default_post.prf:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\win32\console.prf:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\c++11.prf:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\qt.prf:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\resources.prf:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\moc.prf:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\testlib_defines.prf:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\win32\opengl.prf:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\uic.prf:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\qml_debug.prf:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\declarative_debug.prf:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\win32\rtti.prf:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\precompile_header.prf:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\warn_on.prf:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\testcase_targets.prf:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\exceptions.prf:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\yacc.prf:
F:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\lex.prf:
G:\qgroundcontrol-Stable_V3.0\qgroundcontrol.pro:
F:/Qt/Qt5.5.1/5.5/msvc2013/lib/Qt5Location.prl:
F:/Qt/Qt5.5.1/5.5/msvc2013/lib/Qt5QuickWidgets.prl:
F:/Qt/Qt5.5.1/5.5/msvc2013/lib/Qt5Quick.prl:
F:/Qt/Qt5.5.1/5.5/msvc2013/lib/Qt5OpenGL.prl:
F:/Qt/Qt5.5.1/5.5/msvc2013/lib/Qt5Svg.prl:
F:/Qt/Qt5.5.1/5.5/msvc2013/lib/Qt5PrintSupport.prl:
F:/Qt/Qt5.5.1/5.5/msvc2013/lib/Qt5Widgets.prl:
F:/Qt/Qt5.5.1/5.5/msvc2013/lib/Qt5Gui.prl:
F:/Qt/Qt5.5.1/5.5/msvc2013/lib/Qt5Concurrent.prl:
F:/Qt/Qt5.5.1/5.5/msvc2013/lib/Qt5Positioning.prl:
F:/Qt/Qt5.5.1/5.5/msvc2013/lib/Qt5Qml.prl:
F:/Qt/Qt5.5.1/5.5/msvc2013/lib/Qt5Network.prl:
F:/Qt/Qt5.5.1/5.5/msvc2013/lib/Qt5Sql.prl:
F:/Qt/Qt5.5.1/5.5/msvc2013/lib/Qt5Xml.prl:
F:/Qt/Qt5.5.1/5.5/msvc2013/lib/Qt5SerialPort.prl:
F:/Qt/Qt5.5.1/5.5/msvc2013/lib/Qt5Test.prl:
F:/Qt/Qt5.5.1/5.5/msvc2013/lib/Qt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=declarative_debug" "CONFIG+=qml_debug" -o Makefile G:\qgroundcontrol-Stable_V3.0\qgroundcontrol.pro

qmake_all: FORCE

make_first: debug-make_first release-make_first  FORCE
all: debug-all release-all  FORCE
clean: debug-clean release-clean  FORCE
	-$(DEL_FILE) obj\QGroundControl_pch.pch
	-$(DEL_FILE) debug\QGroundControl0.exp
	-$(DEL_FILE) debug\QGroundControl0.ilk
	-$(DEL_FILE) debug\QGroundControl0.idb
distclean: debug-distclean release-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) debug\QGroundControl0.lib debug\QGroundControl0.pdb

debug-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocclean
release-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocclean
mocclean: debug-mocclean release-mocclean

debug-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocables
release-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocables
mocables: debug-mocables release-mocables

check: first
FORCE:

$(MAKEFILE).Debug: Makefile
$(MAKEFILE).Release: Makefile
